#!/usr/bin/env bash

LTS_VERSION=${VERSION:-8.15}
STACKAGE_BUILD_PLAN_DIR=${STACKAGE_BUILD_PLAN_DIR:-~/lts-haskell}
ALL_CABAL_HASHES_DIR=${ALL_CABAL_HASHES_DIR:-~/all-cabal-hashes}

if [ ! -d "$STACKAGE_BUILD_PLAN_DIR" ]; then
  git clone --depth 1 https://github.com/fpco/lts-haskell.git "$STACKAGE_BUILD_PLAN_DIR"
fi

if [ ! -d "$ALL_CABAL_HASHES_DIR" ]; then
  git clone --depth 1 --branch hackage https://github.com/commercialhaskell/all-cabal-hashes.git "$ALL_CABAL_HASHES_DIR"
fi

set -x
stack exec -- stack2nix \
  --stackage-build-plan "$STACKAGE_BUILD_PLAN_DIR/lts-$LTS_VERSION.yaml" \
  --all-cabal-hashes "$ALL_CABAL_HASHES_DIR"
set +x

nix-build -A stack2nix "$@"
