#!/usr/bin/env bash

set -e

LTS_HASKELL_DIR=${LTS_HASKELL_DIR:-~/lts-haskell}
ALL_CABAL_HASHES_DIR=${ALL_CABAL_HASHES_DIR:-~/all-cabal-hashes}

if [ ! -d "$LTS_HASKELL_DIR" ]; then
  git clone --depth 1 https://github.com/fpco/lts-haskell.git "$LTS_HASKELL_DIR"
fi

if [ ! -d "$ALL_CABAL_HASHES_DIR" ]; then
  git clone --depth 1 --branch hackage https://github.com/commercialhaskell/all-cabal-hashes.git "$ALL_CABAL_HASHES_DIR"
fi

set -x
stack exec -- stack2nix \
  --lts-haskell "$LTS_HASKELL_DIR" \
  --all-cabal-hashes "$ALL_CABAL_HASHES_DIR" \
  .

nix-build -A stack2nix "$@"
