# Generated by stackage2nix 0.5.0 from "../../stack-ghc-822.yaml"
{ nixpkgs ? import <nixpkgs> {} }:

with nixpkgs;
let
  inherit (stdenv.lib) extends;
  haskellLib = callPackage (nixpkgs.path + "/pkgs/development/haskell-modules/lib.nix") {};
  stackagePackages = import ./packages.nix;
  stackageConfig = import  ./configuration-packages.nix { inherit pkgs haskellLib; };
  stackPackages =
    { pkgs, stdenv, callPackage }:
    
    self: {
      "stackage2nix" = callPackage
        ({ mkDerivation, aeson, base, bytestring, Cabal, cabal2nix
         , containers, deepseq, distribution-nixpkgs, exceptions, filepath
         , gitlib, gitlib-libgit2, hopenssl, hspec, inflections
         , language-nix, lens, network-uri, optparse-applicative, pretty
         , QuickCheck, shakespeare, stackage-curator, text
         , unordered-containers, yaml
         }:
         mkDerivation {
           pname = "stackage2nix";
           version = "0.5.0";
           src = ../../.;
           isLibrary = true;
           isExecutable = true;
           libraryHaskellDepends = [
             aeson base bytestring Cabal cabal2nix containers deepseq
             distribution-nixpkgs exceptions filepath gitlib gitlib-libgit2
             hopenssl inflections language-nix lens network-uri
             optparse-applicative pretty QuickCheck stackage-curator text
             unordered-containers yaml
           ];
           executableHaskellDepends = [ base ];
           testHaskellDepends = [
             base bytestring Cabal hspec pretty shakespeare text yaml
           ];
           homepage = "https://github.com/typeable/stackage2nix#readme";
           description = "Convert Stack files into Nix build instructions";
           license = stdenv.lib.licenses.bsd3;
         }) {};
    };
  
  pkgOverrides = self: stackPackages {
    inherit pkgs stdenv;
    inherit (self) callPackage;
  };
  
in callPackage (nixpkgs.path + "/pkgs/development/haskell-modules") {
  ghc = pkgs.haskell.compiler.ghc822;
  compilerConfig = self: extends pkgOverrides (stackageConfig self);
  initialPackages = stackagePackages;
  configurationCommon = args: self: super: {};
  inherit haskellLib;
}
